-- BCS-DEF-4-TG (2026-05-20) — one-time binding codes for the learner ↔
-- chat_id handshake. Single-use; 10-min TTL; learner-scoped.
--
-- Plan: docs/plans/bcs-def-4-tg-telegram-reminders.md §2.3.
--
-- Storage of learner_telegram_enabled + learner_telegram_chat_id lives
-- on the `accounts` table (migration 0065). This table holds only the
-- 8-char-code TTL state used during the binding handshake.
--
-- ACCESS EXCLUSIVE briefly on the new table during creation; no
-- existing-table modifications (no online migration risk).

create table if not exists learner_telegram_bind_codes (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references accounts(id) on delete cascade,
  code text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz null,
  consumed_chat_id text null,
  -- Code shape: 8-char uppercase alphanumeric (excluding ambiguous
  -- 0/O/1/I). Generated by crypto.randomInt on the issue side.
  -- Stored as text (NOT hashed) — short-lived (10 min) + single-use
  -- + scoped to the learner account, so a leak in this table is bounded.
  constraint ltbc_code_format
    check (code ~ '^[A-Z0-9]{8}$'),
  constraint ltbc_expires_after_created
    check (expires_at > created_at)
);

-- Consumption sanity: consumed_at requires consumed_chat_id at the
-- moment of consumption. Retention scrub later NULLs consumed_chat_id
-- after the bound account is purged; the relaxed CHECK accepts that
-- post-consumption shape ("consumed_at set; consumed_chat_id may be
-- anything").
alter table learner_telegram_bind_codes
  drop constraint if exists ltbc_consumed_consistency;
alter table learner_telegram_bind_codes
  add constraint ltbc_consumed_consistency
  check (
    -- An unconsumed row has both consumed columns null.
    (consumed_at is null and consumed_chat_id is null)
    -- A consumed row has consumed_at set; consumed_chat_id may be NULL
    -- if the retention sweep later scrubbed it after the account was
    -- purged. Either value is acceptable post-consumption.
    or (consumed_at is not null)
  );

-- Index for the webhook /start <code> path — look up by code,
-- restricted to non-consumed + non-expired rows. Partial index keeps
-- this small.
create index if not exists ltbc_active_lookup_idx
  on learner_telegram_bind_codes (code)
  where consumed_at is null;

-- Index for per-account active code (rate-limit "one issued at a time").
create index if not exists ltbc_account_active_idx
  on learner_telegram_bind_codes (account_id)
  where consumed_at is null;

-- Index for retention sweep (find expired rows for cleanup).
create index if not exists ltbc_expires_at_idx
  on learner_telegram_bind_codes (expires_at);

comment on table learner_telegram_bind_codes is
  'BCS-DEF-4-TG (2026-05-20): one-time 8-char codes for the learner '
  'Telegram bind handshake. Learner issues via cabinet → /start <code> '
  'webhook consumes → accounts.learner_telegram_{enabled,chat_id} set. '
  '10-min TTL; single-use; account-scoped. Retention sweep deletes '
  'expired-unconsumed rows daily and scrubs consumed_chat_id when the '
  'bound account is purged (152-FZ).';
